USE OLYMPICARCHERY;

-- QUESTION 1
SELECT FName, LName FROM PARTICIPANT;

-- QUESTION 2
SELECT OlympicID FROM ATHLETE WHERE Sex='M' AND FirstGames='Rio 2016';

-- QUESTION 3
SELECT Country, LName, BirthYear FROM PARTICIPANT P, ATHLETE A WHERE P.OlympicID=A.OlympicID;

-- QUESTION 4
SELECT FName, Country FROM PARTICIPANT P, COACH C WHERE P.OlympicID=C.OlympicID AND Orientation='Complete';

-- QUESTION 5
CREATE TEMPORARY TABLE BRONZE_MEDALISTS AS SELECT Olympian FROM INDIVIDUAL_RESULTS WHERE Medal='Bronze';
SELECT FirstGames FROM ATHLETE A, BRONZE_MEDALISTS B WHERE A.OlympicID=B.Olympian;

-- QUESTION 6
CREATE TEMPORARY TABLE INDIVIDUAL_GOLD AS SELECT I.Olympian Olympian FROM INDIVIDUAL_RESULTS I WHERE I.Medal='Gold';
CREATE TEMPORARY TABLE TEAM_GOLD AS SELECT Member1 Olympian FROM TEAM, TEAM_RESULTS WHERE TEAM.TeamID=TEAM_RESULTS.TEAM AND Medal='Gold';
CREATE TEMPORARY TABLE ALL_GOLD AS SELECT * FROM INDIVIDUAL_GOLD UNION SELECT * FROM TEAM_GOLD;
SELECT DISTINCT Country FROM PARTICIPANT P, ALL_GOLD A WHERE P.OlympicID=A.Olympian;

-- QUESTION 7
CREATE TEMPORARY TABLE ALL_COUNTRIES AS SELECT DISTINCT Country FROM PARTICIPANT;
CREATE TEMPORARY TABLE GOLD_COUNTRIES AS SELECT Country FROM PARTICIPANT P, ALL_GOLD A WHERE P.OlympicID=A.Olympian;
SELECT * FROM ALL_COUNTRIES WHERE Country NOT IN (SELECT Country FROM GOLD_COUNTRIES);

-- QUESTION 8
SELECT BirthYear FROM EVENT_SCHEDULE E, INDIVIDUAL_RESULTS I, ATHLETE A WHERE I.EventID=E.EventID AND (EventDate='July 30' OR EventDate='July 31') AND A.OlympicID=I.Olympian;
